language: php

branches:
  only:
    - master
    - dev

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - pip install --user codecov

install:
  - composer self-update
  - composer install -n --prefer-source

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpcs --standard=./phpcs.xml -v --encoding=utf-8 ./src
  - vendor/bin/phpunit -c phpunit.xml --debug

after_success:
  - codecov

